### ISSUE TITLE
Possible Dust Removal Improvements

### ISSUE THREAD

**Issue by william-silversmith** [MICLab-Unicamp/HypAST#1]
Hi! This is a cool project! I don't know if this is helpful or not, but I was just checking through some recent users of cc3d to see how it was being used as I recently added a new function `cc3d.dust` in the lastest cc3d that may be more performant than a typical implementation of dust removal. It's always hard for me to know whether this is helpful for a given project, but sometimes the CCL component can end up being a bottleneck.

I noticed that in these two spots could be simplified and most probably be made faster (depends on whether your data are mostly smooth or very noisy, random noise could be slower).

https://github.com/MICLab-Unicamp/HypAST/blob/master/hypast/Predictor.py#L51-L55

```python
labels_out = cc3d.dust((final_seg>0.8).astype(np.uint8), threshold=50)
```
https://github.com/MICLab-Unicamp/HypAST/blob/master/hypast/Predictor.py#L59-L63

```python
labels_out = cc3d.dust((final_seg>0.2).astype(np.uint8), threshold=50)
```

If this isn't helpful, please feel free to ignore. The last thing I'd want to do is waste your time. 

Thanks for reading and doing science!

**Comment by liviamarodrigues** [comment]
Hi, William! Thanks so much for your comment! I'll check the cc3d.dust function for sure!
If it improves the performance of the code, I'll update it. 
Thanks!
